# src/gencysynth/orchestration/run_spec.py
"""
GenCyberSynth — RunSpec (what to run)
====================================

A RunSpec is a *portable, serializable* description of one execution unit:
  - which dataset to use (dataset_id + dataset config)
  - which model to run (model_tag + variant config)
  - what the run_id/seed is
  - where outputs should be written (derived, not user_authored)
  - optional sweep metadata (suite_id, grid_id, slurm task id, etc.)

Why this exists
---------------
We scale across:
  datasets × model_families × variants × seeds × budgets × sweeps

So we need a stable run descriptor that can be:
  - generated by a suite builder
  - executed by local CLI or Slurm array worker
  - logged and audited later

This file contains only *data structures + helpers*.
Execution belongs in orchestration/harvester.py (or model pipelines).
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any, Dict, Optional


@dataclass(frozen=True)
class RunSpec:
    """
    Canonical run specification.

    Notes
    -----
    - dataset_id, model_tag, run_id are the primary keys for artifacts layout.
    - cfg is the merged configuration for this run (dataset+model+base+overrides).
    """
    dataset_id: str
    model_tag: str
    run_id: str
    seed: int

    # Optional: suite/sweep metadata for HPC aggregation
    suite_id: Optional[str] = None
    grid_id: Optional[str] = None
    task_id: Optional[int] = None

    # The effective runtime config for the run (YAML merged output)
    cfg: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """JSON_serializable dict (dataclass -> dict)."""
        return asdict(self)


__all__ = ["RunSpec"]
