# src/gencysynth/metrics/types.py
"""
Core types for the GenCyberSynth metrics layer.

Rule A goals
------------
- Stable, typed-ish interfaces for metric computation.
- JSON-friendly result containers.
- No heavy dependencies (NumPy only here).

This file deliberately does *not* import project-specific config/hashing/etc.
Those live in gencysynth.utils.* and are used by api/writer/config.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Protocol, Sequence, Tuple, Union

import numpy as np


Json = Dict[str, Any]


@dataclass(frozen=True)
class DatasetMeta:
    """
    Minimal dataset identity/shape metadata for metrics.

    dataset_id
      Stable identifier for the dataset (preferred: cfg["data"]["id"]).
      Fallback can be derived from cfg["data"]["root"].

    img_shape
      Channels-last shape (H, W, C).
    """
    dataset_id: str
    img_shape: Tuple[int, int, int]
    num_classes: int


@dataclass(frozen=True)
class RunMeta:
    """
    Minimal run identity metadata for metrics outputs.

    run_id
      Stable run identifier; ideally generated by the orchestrator.
      Metrics package will accept it; if missing, api/config will generate a safe fallback.

    seed
      Seed used for synthetic generation or evaluation.
    """
    run_id: str
    seed: int = 42
    tags: Dict[str, Any] = field(default_factory=dict)


@dataclass
class MetricResult:
    """
    The output of a single metric computation.

    Fields are JSON-serializable:
      - name: metric name (registry key)
      - value: a float scalar (if applicable)
      - details: structured details (dict/list/nums)
      - artifacts: metric-specific files written (paths, figures, etc.)
    """
    name: str
    value: Optional[float] = None
    details: Dict[str, Any] = field(default_factory=dict)
    artifacts: Dict[str, str] = field(default_factory=dict)
    status: str = "ok"  # {"ok","skipped","error"}
    error: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "value": self.value,
            "details": self.details,
            "artifacts": self.artifacts,
            "status": self.status,
            "error": self.error,
        }


class Metric(Protocol):
    """
    Metric callable contract.

    Inputs
    ------
    x_real01: float32 in [0,1], shape (N,H,W,C)
    y_real  : int labels (N,) or one-hot (N,K) OR None (some metrics are unconditional)

    x_synth01: float32 in [0,1], shape (M,H,W,C)
    y_synth  : int labels (M,) or one-hot (M,K) OR None

    meta: dataset + run metadata for labeling output

    cfg: the full config dict (metric may read metric-specific knobs)

    Returns
    -------
    MetricResult
    """
    def __call__(
        self,
        *,
        x_real01: np.ndarray,
        y_real: Optional[np.ndarray],
        x_synth01: np.ndarray,
        y_synth: Optional[np.ndarray],
        dataset: DatasetMeta,
        run: RunMeta,
        cfg: Dict[str, Any],
    ) -> MetricResult: ...


def as_float01(x: np.ndarray) -> np.ndarray:
    """
    Normalize images to float32 in [0,1] without changing shape.
    Supports inputs in [0,255] or already [0,1].
    """
    x = np.asarray(x).astype(np.float32, copy=False)
    if x.size == 0:
        return x
    if float(np.nanmax(x)) > 1.5:
        x = x / 255.0
    return np.clip(x, 0.0, 1.0)


def as_int_labels(y: Optional[np.ndarray], num_classes: int) -> Optional[np.ndarray]:
    """
    Convert labels to int64 vector if provided.
    Accepts (N,) ints or (N,K) one-hot.
    """
    if y is None:
        return None
    y = np.asarray(y)
    if y.ndim == 2 and y.shape[1] == int(num_classes):
        return np.argmax(y, axis=1).astype(np.int64)
    return y.reshape(-1).astype(np.int64)
